services:
  - type: web
    name: gemini-web2api-easy
    runtime: docker
    plan: free
    dockerfilePath: ./deploy/Dockerfile
    region: frankfurt
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
      - key: API_KEY
        generateValue: true
      - fromGroup: gemini-secrets

envVarGroups:
  - name: gemini-secrets
    envVars:
      - key: EASY_SUB_URL
        sync: false